/**
 * In-browser mock backend implementing the same contract as /workspace/portfolio-backend.
 * Enabled when VITE_USE_MOCKS !== "false". All content here is SAMPLE data.
 * State persists in localStorage so the /admin editor and /blog stay in sync.
 */
import { MOCK_ADMIN_PASSWORD } from '../lib/config'
import { slugify } from '../lib/slug'
import { isHttpUrl } from '../lib/url'
import type { AdminPost, AdminPostInput, ContactInput, GithubResponse, PostStatus } from './types'

const STORE_KEY = 'portfolio-mock-posts-v2'
const AUTH_KEY = 'portfolio-mock-auth'

const day = 24 * 60 * 60 * 1000
const iso = (t: number) => new Date(t).toISOString()

function seedPosts(): AdminPost[] {
  const now = Date.now()
  const mk = (
    id: number,
    title: string,
    slug: string,
    content: string,
    offsetDays: number,
    status: PostStatus,
    sourceUrl: string | null = null,
  ): AdminPost => ({
    id,
    sourceUrl,
    slug,
    title,
    content,
    status,
    publishedAt: iso(now + offsetDays * day),
    updatedAt: iso(now + Math.min(offsetDays, 0) * day),
  })
  const note =
    '> **This is sample content** generated by the frontend mock layer. Real posts are written in `/admin` and served by the backend.\n\n'
  return [
    mk(
      1,
      'Sample post: Building a scam detector in a weekend',
      'sample-building-a-scam-detector',
      note +
        '## Placeholder heading\n\nThis placeholder shows how a longer post renders: paragraphs, **bold text**, `inline code`, and lists.\n\n- First point\n- Second point\n- Third point\n\n```ts\nconst greeting: string = "hello, recruiters"\nconsole.log(greeting)\n```\n\nReplace this with a real write-up.',
      -2,
      'published',
    ),
    mk(
      2,
      'Sample post: Notes from my home lab',
      'sample-notes-from-my-home-lab',
      note +
        '## Placeholder\n\nA sample post to demo the blog layout. Nothing here describes real events.\n\n1. Step one\n2. Step two\n3. Step three\n\n*Sample: this mock post carries a placeholder `sourceUrl` so the "View on LinkedIn" link can be previewed. It does not point to a real post.*',
      -9,
      'published',
      'https://www.linkedin.com/feed/update/urn:li:activity:0000000000000000000/',
    ),
    mk(
      3,
      'Sample post: What I learned at a hackathon',
      'sample-what-i-learned-at-a-hackathon',
      note + 'Lorem ipsum style filler text for layout testing. Swap in a real post from the admin editor.',
      -20,
      'published',
    ),
    mk(
      4,
      'Sample post: Markdown rendering test',
      'sample-markdown-rendering-test',
      note +
        '# H1\n## H2\n### H3\n\n*Italic*, **bold**, [a link](https://example.com).\n\n> A blockquote.\n\n| Col A | Col B |\n|---|---|\n| 1 | 2 |',
      -35,
      'published',
    ),
    mk(5, 'Sample post: Placeholder for layout', 'sample-placeholder-for-layout', note + 'Short filler post.', -50, 'published'),
    mk(6, 'Sample post: Another placeholder', 'sample-another-placeholder', note + 'More filler to show pagination.', -64, 'published'),
    mk(7, 'Sample draft (hidden from the public blog)', 'sample-draft', note + 'Drafts never appear on /blog.', -1, 'draft'),
    mk(8, 'Sample scheduled post (publishes in 3 days)', 'sample-scheduled', note + 'Scheduled posts return 404 until their publish time.', 3, 'published'),
  ]
}

function loadPosts(): AdminPost[] {
  try {
    const raw = localStorage.getItem(STORE_KEY)
    if (raw) return JSON.parse(raw) as AdminPost[]
  } catch {
    /* ignore */
  }
  const seeded = seedPosts()
  savePosts(seeded)
  return seeded
}

function savePosts(posts: AdminPost[]): void {
  try {
    localStorage.setItem(STORE_KEY, JSON.stringify(posts))
  } catch {
    /* ignore */
  }
}

const isAuthed = () => sessionStorage.getItem(AUTH_KEY) === '1'

// Same helpers as the backend's posts-repo.ts
function excerptOf(markdown: string, max = 180): string {
  const plain = markdown
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ')
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
    .replace(/[#>*_`~-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
  return plain.length <= max ? plain : plain.slice(0, max).replace(/\s+\S*$/, '') + '…'
}

const isPublic = (p: AdminPost, now: number) => p.status === 'published' && Date.parse(p.publishedAt) <= now
const byDateDesc = (a: AdminPost, b: AdminPost) => Date.parse(b.publishedAt) - Date.parse(a.publishedAt) || b.id - a.id

function json(status: number, body: unknown): Response {
  return new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } })
}
const err = (status: number, code: string, message: string) => json(status, { error: { code, message } })

function validatePostInput(b: Partial<AdminPostInput>): string | null {
  if (!b.title || !b.title.trim()) return 'title: Required'
  if (!b.content || !b.content.trim()) return 'content: Required'
  if (!b.publishedAt || Number.isNaN(Date.parse(b.publishedAt))) return 'publishedAt: Invalid datetime'
  if (b.status !== 'draft' && b.status !== 'published') return 'status: Invalid option'
  if (b.sourceUrl && !isHttpUrl(b.sourceUrl)) return 'sourceUrl: must be an http(s) URL'
  if (b.slug !== undefined && !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(b.slug)) return 'slug: use lowercase letters, numbers and dashes'
  return null
}

const contactLog: number[] = []

const sampleGithub = (): GithubResponse => {
  const now = Date.now()
  return {
    repos: [
      {
        name: 'sample-repo-one',
        description: 'SAMPLE DATA: placeholder repository card. Live data loads from /api/github when the backend is connected.',
        url: 'https://github.com/siyadyusuf',
        language: 'TypeScript',
        stars: 0,
        updatedAt: iso(now - 1 * day),
      },
      {
        name: 'sample-repo-two',
        description: 'SAMPLE DATA: placeholder repository card.',
        url: 'https://github.com/siyadyusuf',
        language: 'Python',
        stars: 0,
        updatedAt: iso(now - 6 * day),
      },
      {
        name: 'sample-repo-three',
        description: 'SAMPLE DATA: placeholder repository card.',
        url: 'https://github.com/siyadyusuf',
        language: 'JavaScript',
        stars: 0,
        updatedAt: iso(now - 15 * day),
      },
      {
        name: 'sample-repo-four',
        description: null,
        url: 'https://github.com/siyadyusuf',
        language: null,
        stars: 0,
        updatedAt: iso(now - 40 * day),
      },
    ],
    recentActivity: [
      { type: 'PushEvent', repo: 'siyadyusuf/sample-repo-one', message: 'Pushed 2 commits: sample commit message', url: 'https://github.com/siyadyusuf', createdAt: iso(now - 3 * 3600_000) },
      { type: 'CreateEvent', repo: 'siyadyusuf/sample-repo-two', message: 'Created branch sample-branch', url: 'https://github.com/siyadyusuf', createdAt: iso(now - 1.2 * day) },
      { type: 'PullRequestEvent', repo: 'siyadyusuf/sample-repo-one', message: 'opened pull request: Sample PR title', url: 'https://github.com/siyadyusuf', createdAt: iso(now - 2.5 * day) },
      { type: 'PushEvent', repo: 'siyadyusuf/sample-repo-three', message: 'Pushed 1 commit: sample commit message', url: 'https://github.com/siyadyusuf', createdAt: iso(now - 5 * day) },
    ],
    contributions: sampleContributions(now),
  }
}

/** SAMPLE DATA: a sparse, deterministic calendar so the heatmap has something to show in mock mode. */
function sampleContributions(now: number): GithubResponse['contributions'] {
  const days: { date: string; count: number }[] = []
  let seed = 7
  const rand = () => ((seed = (seed * 16807) % 2147483647) / 2147483647)
  for (let i = 364; i >= 0; i--) {
    const d = new Date(now - i * day)
    const date = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
    const recent = i < 60 ? 0.22 : 0.06
    const r = rand()
    days.push({ date, count: r < recent ? 1 + Math.floor(rand() * (i < 30 ? 7 : 3)) : 0 })
  }
  return { total: days.reduce((s, d) => s + d.count, 0), days }
}

const delay = (ms: number) => new Promise((r) => setTimeout(r, ms))

export async function mockFetch(input: string, init: RequestInit): Promise<Response> {
  await delay(180 + Math.random() * 200)
  const url = new URL(input, window.location.origin)
  const path = url.pathname.replace(/^\/api/, '')
  const method = (init.method ?? 'GET').toUpperCase()
  let body: Record<string, unknown> = {}
  if (typeof init.body === 'string') {
    try {
      body = JSON.parse(init.body) as Record<string, unknown>
    } catch {
      return err(400, 'validation_error', 'body: Invalid JSON')
    }
  }
  const now = Date.now()

  // ---- Public posts
  if (method === 'GET' && path === '/posts') {
    const page = Math.max(1, parseInt(url.searchParams.get('page') ?? '1', 10) || 1)
    const limit = Math.min(50, Math.max(1, parseInt(url.searchParams.get('limit') ?? '10', 10) || 10))
    const pub = loadPosts().filter((p) => isPublic(p, now)).sort(byDateDesc)
    const slice = pub.slice((page - 1) * limit, page * limit)
    return json(200, {
      posts: slice.map((p) => ({ id: p.id, slug: p.slug, title: p.title, excerpt: excerptOf(p.content), publishedAt: p.publishedAt, sourceUrl: p.sourceUrl ?? null })),
      page,
      totalPages: Math.max(1, Math.ceil(pub.length / limit)),
    })
  }
  const postMatch = path.match(/^\/posts\/([^/]+)$/)
  if (method === 'GET' && postMatch) {
    const slug = decodeURIComponent(postMatch[1])
    const p = loadPosts().find((x) => x.slug === slug && isPublic(x, now))
    if (!p) return err(404, 'not_found', 'Post not found')
    return json(200, { id: p.id, slug: p.slug, title: p.title, content: p.content, publishedAt: p.publishedAt, updatedAt: p.updatedAt, sourceUrl: p.sourceUrl ?? null })
  }

  // ---- Auth
  if (method === 'POST' && path === '/auth/login') {
    if (body.password !== MOCK_ADMIN_PASSWORD) return err(401, 'invalid_password', 'Wrong password')
    sessionStorage.setItem(AUTH_KEY, '1')
    return json(200, { ok: true })
  }
  if (method === 'POST' && path === '/auth/logout') {
    sessionStorage.removeItem(AUTH_KEY)
    return json(200, { ok: true })
  }
  if (method === 'GET' && path === '/auth/me') return json(200, { authenticated: isAuthed() })

  // ---- Admin posts
  if (path.startsWith('/admin/posts')) {
    if (!isAuthed()) return err(401, 'unauthorized', 'Please log in')
    const posts = loadPosts()
    const idMatch = path.match(/^\/admin\/posts\/(\d+)$/)
    if (method === 'GET' && path === '/admin/posts') return json(200, { posts: [...posts].sort(byDateDesc) })
    if (method === 'POST' && path === '/admin/posts') {
      const input = body as Partial<AdminPostInput>
      const v = validatePostInput(input)
      if (v) return err(400, 'validation_error', v)
      let slug = input.slug
      if (slug) {
        if (posts.some((p) => p.slug === slug)) return err(409, 'slug_taken', 'That slug is already used')
      } else {
        const base = slugify(input.title!)
        slug = base
        for (let i = 2; posts.some((p) => p.slug === slug); i++) slug = `${base}-${i}`
      }
      const created: AdminPost = {
        id: posts.reduce((m, p) => Math.max(m, p.id), 0) + 1,
        slug,
        title: input.title!.trim(),
        content: input.content!,
        status: input.status!,
        publishedAt: new Date(input.publishedAt!).toISOString(),
        updatedAt: iso(now),
        sourceUrl: input.sourceUrl || null,
      }
      savePosts([...posts, created])
      return json(201, created)
    }
    if (idMatch) {
      const id = Number(idMatch[1])
      const existing = posts.find((p) => p.id === id)
      if (!existing) return err(404, 'not_found', 'Post not found')
      if (method === 'GET') return json(200, existing)
      if (method === 'PUT') {
        const input = body as Partial<AdminPostInput>
        const v = validatePostInput(input)
        if (v) return err(400, 'validation_error', v)
        const slug = input.slug ?? existing.slug
        if (posts.some((p) => p.slug === slug && p.id !== id)) return err(409, 'slug_taken', 'That slug is already used')
        const updated: AdminPost = {
          ...existing,
          slug,
          title: input.title!.trim(),
          content: input.content!,
          status: input.status!,
          publishedAt: new Date(input.publishedAt!).toISOString(),
          updatedAt: iso(now),
          sourceUrl: input.sourceUrl === undefined ? (existing.sourceUrl ?? null) : input.sourceUrl || null,
        }
        savePosts(posts.map((p) => (p.id === id ? updated : p)))
        return json(200, updated)
      }
      if (method === 'DELETE') {
        savePosts(posts.filter((p) => p.id !== id))
        return json(200, { ok: true })
      }
    }
  }

  // ---- Contact (5 per hour, like the backend)
  if (method === 'POST' && path === '/contact') {
    const input = body as Partial<ContactInput>
    const hourAgo = now - 3600_000
    while (contactLog.length && contactLog[0] < hourAgo) contactLog.shift()
    if (contactLog.length >= 5) return err(429, 'rate_limited', "You've sent a few messages already, try again later")
    contactLog.push(now)
    if (!input.name?.trim()) return err(400, 'validation_error', 'name: Required')
    if (!input.email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(input.email)) return err(400, 'validation_error', 'email: Invalid email address')
    if (!input.message?.trim()) return err(400, 'validation_error', 'message: Required')
    // Honeypot filled: pretend success, send nothing (same as backend).
    return json(200, { ok: true })
  }

  // ---- GitHub
  if (method === 'GET' && path === '/github') {
    // Preview empty states in mock mode: add ?mockGithub=empty (no data) or ?mockGithub=null (contributions: null) to the page URL.
    const mode = new URLSearchParams(window.location.search).get('mockGithub')
    if (mode === 'empty') return json(200, { repos: [], recentActivity: [], contributions: { total: 0, days: [] } })
    if (mode === 'null') return json(200, { ...sampleGithub(), contributions: null })
    return json(200, sampleGithub())
  }

  return err(404, 'not_found', 'No such endpoint')
}

export function resetMockData(): void {
  localStorage.removeItem(STORE_KEY)
}
